### ISSUE TITLE
Delete master branch as devel has superseded it

### ISSUE THREAD

**Issue by mblue9** [Bioconductor/bioconductor-teaching#37]
Hi @csoneson, @lgatto,

Could one of you please delete the master branch in this repo? Since devel is the current active branch, removing master will help prevent people from making PRs to the wrong branch. This issue came up with Ouso's PR: https://github.com/Bioconductor/bioconductor-teaching/pull/33, where the data wasn't added because the PR was made to master instead of devel. (I've now added Ouso's data to the new instructors table in devel).

I don't have permission to delete the branch myself, but it would be great if we could do this to avoid future issues.

Thanks!

**Comment by csoneson** [comment]
I have deleted the `master` branch.
